// LaboratorIA — datos del curso. Fuente única compartida con la guía en Word.
window.LAB_DATA = {
  piensa: [
    { l: 'P', t: 'Propósito', d: '¿Qué quiero lograr exactamente con esto?' },
    { l: 'I', t: 'Información', d: '¿Qué contexto o datos necesita saber la IA?' },
    { l: 'E', t: 'Ejemplo / formato', d: '¿Cómo quiero que se vea la respuesta?' },
    { l: 'N', t: 'Nivel de detalle', d: '¿Qué tan simple o profundo debe ser?' },
    { l: 'S', t: 'Superviso', d: 'Leo con sentido común. ¿Tiene lógica? ¿Hay algo raro?' },
    { l: 'A', t: 'Ajusto', d: 'Si no sirve, cambio algo puntual y repito. Iterar, no memorizar.' },
  ],
  detector: [
    '¿Esto suena demasiado perfecto o específico sin ninguna fuente?',
    '¿Puedo verificarlo con otra fuente, o con algo que ya sé con certeza?',
    '¿La IA está afirmando con mucha confianza algo que, si lo pienso, no podría saber?',
  ],
  niveles: [
    { min: 0, max: 20, nombre: 'Aprendiz de Chispa', icon: '◆' },
    { min: 21, max: 45, nombre: 'Explorador Rayo', icon: '◈' },
    { min: 46, max: 70, nombre: 'Estratega Rayo', icon: '⚡' },
    { min: 71, max: 999, nombre: 'Maestro IA', icon: '🏆' },
  ],
  edades: [
    { plataforma: 'ChatGPT (OpenAI)', edad: '13+', detalle: 'Entre 13 y 17 requiere consentimiento de padre/tutor. Existe un modo "ChatGPT for Teens".', url: 'https://help.openai.com/en/articles/8313401-is-chatgpt-safe-for-all-ages' },
    { plataforma: 'Claude (Anthropic)', edad: '18+', detalle: 'Sin excepción ni ruta de consentimiento parental. Úsalo junto a ellos, bajo tu cuenta.', url: 'https://support.claude.com/en/articles/15171100-age-assurance-on-claude' },
    { plataforma: 'Gemini (Google)', edad: '13+', detalle: 'Cuenta personal a partir de 13 años; menores de 13 requieren Family Link.', url: 'https://gemini.google.com' },
    { plataforma: 'Perplexity', edad: '13+', detalle: 'Menores de 13 a 17 pueden usarlo solo si el padre/tutor acepta los Términos en su nombre.', url: 'https://www.perplexity.ai/es/hub/legal/terms-of-service' },
    { plataforma: 'Midjourney', edad: '13+', detalle: 'Se usa a través de Discord, cuya edad mínima general es 13 años.', url: 'https://www.midjourney.com' },
    { plataforma: 'NotebookLM, Leonardo AI, Canva, Suno, ElevenLabs', edad: '13+', detalle: 'Norma general de la mayoría de apps web; acepta los términos la primera vez para cada una.', url: 'https://notebooklm.google.com' },
  ],
  glosario: [
    { t: 'IA generativa', d: 'Sistema que crea texto, imagen, voz o video nuevo, combinando patrones aprendidos de grandes cantidades de datos.' },
    { t: 'LLM (modelo de lenguaje)', d: 'Tipo de IA entrenada con enormes cantidades de texto para predecir la palabra más probable que sigue.' },
    { t: 'Prompt', d: 'La instrucción o pregunta que le escribes a una IA.' },
    { t: 'Alucinación', d: 'Cuando una IA inventa un dato o hecho falso, pero lo presenta con total seguridad.' },
    { t: 'Multimodal', d: 'Una IA que entiende y genera más de un tipo de contenido (texto, imagen, audio, video) a la vez.' },
    { t: 'Agente de IA', d: 'Un sistema que no solo responde, sino que ejecuta pasos y tareas por sí mismo para cumplir un objetivo.' },
    { t: 'Automatización', d: 'Encadenar pasos ("si pasa esto, entonces haz esto") para que una tarea se repita sola.' },
    { t: 'RAG (recuperación aumentada)', d: 'Cuando una IA busca información real (documentos o la web) antes de responder, en vez de solo "recordar".' },
  ],
  reglas: [
    'Privacidad primero: nunca escriban en un chat de IA el nombre completo, dirección, colegio o datos financieros de la familia.',
    'Nunca sin consentimiento: no generar imagen, voz o video de una persona real (conocida o famosa) sin su permiso explícito.',
    'Verificar antes de creer: toda afirmación importante se revisa con el detector de alucinaciones.',
    'Honestidad académica: si usas IA en una tarea del colegio, debes poder explicarla sin ella.',
    'Pausas de pantalla en Ruta Rayo: cada sprint termina con el cronómetro apagado.',
    'Cuentas y edades: papá acompaña la creación de cualquier cuenta nueva.',
    'Avisar siempre: si una conversación con una IA incomoda o pide información rara, se cuenta a papá de inmediato.',
  ],
  fuentes: [
    { t: 'Panorama de herramientas de IA 2026 — aprender21.com', url: 'https://www.aprender21.com/blog/mejores-herramientas-inteligencia-artificial-2026' },
    { t: 'Herramientas de IA 2026 por categoría — DonWeb', url: 'https://blog.donweb.com/mejores-herramientas-ia-2026-por-categoria/' },
    { t: 'Mejores herramientas de IA — Synthesia', url: 'https://www.synthesia.io/es/post/herramientas-de-ia' },
    { t: 'Gamificación y TDAH — Frontiers in Education, 2025', url: 'https://www.frontiersin.org/journals/education/articles/10.3389/feduc.2025.1668260/full' },
    { t: 'Intervenciones digitales basadas en juego — PMC / NIH, 2022', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9379781/' },
    { t: 'Meta-análisis TDAH y videojuegos — European Child & Adolescent Psychiatry, 2025', url: 'https://link.springer.com/article/10.1007/s00787-025-02788-5' },
    { t: 'Edad mínima ChatGPT — OpenAI Help Center', url: 'https://help.openai.com/en/articles/8313401-is-chatgpt-safe-for-all-ages' },
    { t: 'Edad mínima Claude — Anthropic Support', url: 'https://support.claude.com/en/articles/15171100-age-assurance-on-claude' },
    { t: 'Términos de servicio — Perplexity', url: 'https://www.perplexity.ai/es/hub/legal/terms-of-service' },
  ],
  weeks: [
    {
      n: 1,
      titulo: 'Cómo piensa (y cómo NO piensa) una IA',
      mision: 'Descubrir qué hay detrás del chat: una IA no "sabe" cosas como una persona — predice la palabra más probable según patrones aprendidos. Por eso puede sonar segurísima y estar completamente equivocada.',
      porque: 'Esta es la única semana que enseña una idea, no una herramienta. Si entienden ESTA lógica, van a poder usar cualquier IA que exista hoy o que salga en cinco años, sin depender de un tutorial.',
      tools: [
        { name: 'ChatGPT', use: 'Chat conversacional general', url: 'https://chatgpt.com', age: '13+' },
        { name: 'Claude', use: 'Razonamiento y análisis', url: 'https://claude.ai', age: '18+ (con papá)' },
        { name: 'Gemini', use: 'Chat + integración Google', url: 'https://gemini.google.com', age: '13+' },
        { name: 'Perplexity', use: 'Respuestas con fuentes citadas', url: 'https://www.perplexity.ai', age: '13+' },
      ],
      rayo: { resumen: '3 sprints cortos con cronómetro. Cada sprint termina con algo escrito o mostrado.', sprints: [
        { titulo: 'Sprint 1 · Rompe la IA', min: 10, pasos: ['Pon un cronómetro de 10 minutos.', 'Hazle a un chatbot 5 preguntas "trampa": cosas inventadas, imposibles o que no puede saber.', 'Marca si la IA "cayó" y respondió con seguridad algo inventado.', 'Anota cuántas veces cayó de las 5.'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }] },
        { titulo: 'Sprint 2 · Aprende PIENSA con un caso real', min: 10, pasos: ['Elige algo que realmente quieras resolver (rutina de gym, plan de finde, organizar tu cuarto).', 'Pídeselo a una IA aplicando las 6 letras de PIENSA, una por una.', 'No copies la respuesta tal cual: decide qué parte tiene sentido.'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }] },
        { titulo: 'Sprint 3 · Duelo de 2 IAs', min: 15, pasos: ['Haz la MISMA pregunta a dos IAs distintas (ej. ChatGPT y Gemini).', 'Compara: ¿cuál explicó el "por qué" y no solo el "qué"?', 'Elige un ganador y anota en una frase por qué ganó.'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }, { name: 'Gemini', url: 'https://gemini.google.com' }] },
      ] },
      faro: { resumen: '1-2 sesiones más largas, con espacio para escribir y reflexionar en el Cuaderno de IA.', sesiones: [
        { titulo: 'Sesión 1 · ¿Cómo "piensa" un modelo de lenguaje?', min: 45, pasos: ['Investiga qué es un LLM a nivel conceptual: entrenado con enormes cantidades de texto para predecir la palabra siguiente.', 'Escribe: "¿En qué se parece pensar como humano y como IA? ¿En qué se diferencia?"', 'Da un ejemplo propio de algo que una IA podría inventar con confianza.'], salida: [{ name: 'Perplexity', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Sesión 2 · PIENSA aplicado a una decisión real', min: 45, pasos: ['Elige una decisión real pendiente (electiva, plan de estudio, proyecto).', 'Aplica PIENSA en 2 o 3 IAs distintas para la misma decisión.', 'Compara la profundidad del razonamiento de cada una y decide qué harías tú.'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }, { name: 'Gemini', url: 'https://gemini.google.com' }, { name: 'Perplexity', url: 'https://www.perplexity.ai' }] },
      ] },
      encuentro: { titulo: 'Caza de Alucinaciones', duracion: '30 min · todos juntos', pasos: ['Cada uno presenta su pregunta trampa más efectiva.', 'Entre todos votan cuál "engañó" mejor a la IA.', 'Conversen: ¿por qué la IA falló justo ahí?'] },
      auto: ['¿Puedo explicar con mis propias palabras por qué una IA puede "inventar" algo con total seguridad?', '¿Usé las 6 letras de PIENSA sin mirar la chuleta?', '¿Detecté al menos una respuesta dudosa de una IA y la puse en duda?'],
      alerta: 'Nunca compartas nombre completo, dirección, colegio o datos financieros de la familia en un chat de IA. Claude exige 18 años cumplidos sin excepción.',
    },
    {
      n: 2,
      titulo: 'Investigar y razonar con IA',
      mision: 'Usar la IA como copiloto de investigación y de decisiones — nunca como oráculo. La regla de oro: toda afirmación importante necesita una fuente que se pueda revisar.',
      porque: 'La diferencia entre alguien que usa bien la IA y alguien que "le cree todo" no es la herramienta: es el hábito de pedir evidencia y verificar.',
      tools: [
        { name: 'Perplexity', use: 'Investigación con fuentes citadas', url: 'https://www.perplexity.ai', age: '13+' },
        { name: 'NotebookLM', use: 'Resumir y preguntar sobre tus propios apuntes', url: 'https://notebooklm.google.com', age: '13+' },
        { name: 'ChatGPT / Gemini', use: 'Modo "razonar más" para problemas complejos', url: 'https://chatgpt.com', age: '13+' },
      ],
      rayo: { resumen: '3 sprints centrados en investigar rápido y verificar.', sprints: [
        { titulo: 'Sprint 1 · Detective con fuentes', min: 10, pasos: ['Investiga en Perplexity un tema que te apasione (tu equipo, un videojuego, un carro).', 'Encuentra 3 fuentes citadas en la respuesta.', 'Marca cuál fuente es más confiable y por qué.'], salida: [{ name: 'Perplexity', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Sprint 2 · Sube tus apuntes', min: 15, pasos: ['Sube unas notas o un PDF del colegio a NotebookLM.', 'Pídele un resumen y 5 preguntas de repaso.', 'Explica en voz alta la LÓGICA de una respuesta, sin memorizarla.'], salida: [{ name: 'NotebookLM', url: 'https://notebooklm.google.com' }] },
        { titulo: 'Sprint 3 · Reto de planeación', min: 10, pasos: ['Pide a una IA que te ayude a organizar tu semana de estudio con prioridades.', 'Revisa si el orden tiene sentido según tus fechas y energía reales; ajusta lo que no cuadre.'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }] },
      ] },
      faro: { resumen: 'Investigación con criterio + trabajo con apuntes propios.', sesiones: [
        { titulo: 'Sesión 1 · Mini-informe con fuentes', min: 45, pasos: ['Elige un tema de interés e investígalo en Perplexity.', 'Redacta un mini-informe de media página citando al menos 3 fuentes reales.', 'Anota cuál fuente descartarías y por qué.'], salida: [{ name: 'Perplexity', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Sesión 2 · Tus apuntes, verificados', min: 45, pasos: ['Sube tus apuntes de clase a NotebookLM y genera un resumen o audio.', 'Compáralo frase por frase con tu apunte original: ¿qué tan fiel fue?', 'Escribe un caso donde el resumen se equivocó o simplificó de más.'], salida: [{ name: 'NotebookLM', url: 'https://notebooklm.google.com' }] },
      ] },
      encuentro: { titulo: 'El Consejo de las 3 IAs', duracion: '30-40 min · todos juntos', pasos: ['La familia plantea una decisión real y pequeña (restaurante, plan del sábado).', 'Cada hijo consulta una IA distinta para la misma decisión.', 'Comparen las 3 recomendaciones y decidan en familia, con sentido común, cuál seguir.'] },
      auto: ['¿Pedí siempre fuentes o evidencia antes de creer una respuesta importante?', '¿Verifiqué al menos un dato cruzándolo con otra fuente?', '¿Puedo explicar por qué elegí seguir o no la recomendación de una IA?'],
      alerta: 'Las IAs de investigación pueden citar fuentes poco confiables. Antes de creer algo, mira el dominio de la fuente (.edu, .gov, medios reconocidos) y si tiene fecha reciente.',
    },
    {
      n: 3,
      titulo: 'Crear con IA: imagen, video, voz y música',
      mision: 'Entender que estas IAs generan combinando patrones visuales o sonoros aprendidos — no "recuerdan" fotos reales. Por eso a veces fallan en detalles (manos raras, texto ilegible, voces robóticas).',
      porque: 'El mismo método PIENSA que usaron con texto sirve para imagen, video, voz y música: el prompt es el prompt.',
      tools: [
        { name: 'Midjourney', use: 'Imágenes de alta calidad artística', url: 'https://www.midjourney.com', age: '13+' },
        { name: 'Leonardo AI', use: 'Generación de imágenes, plan gratis generoso', url: 'https://leonardo.ai', age: '13+' },
        { name: 'Canva Magic Studio', use: 'Diseño + IA todo en uno', url: 'https://www.canva.com', age: '13+' },
        { name: 'ElevenLabs', use: 'Voz IA / clonación de voz propia', url: 'https://elevenlabs.io', age: '13+' },
        { name: 'Suno', use: 'Composición musical con IA', url: 'https://suno.com', age: '13+' },
        { name: 'Sora (en ChatGPT)', use: 'Video corto a partir de texto', url: 'https://sora.chatgpt.com', age: '13+' },
      ],
      rayo: { resumen: '3 sprints creativos con resultado visible al final de cada uno.', sprints: [
        { titulo: 'Sprint 1 · Cambia una palabra', min: 10, pasos: ['Genera una imagen con un prompt sencillo.', 'Cambia solo UNA palabra del prompt y genera de nuevo. Repite una vez más.', 'Anota qué cambió exactamente con cada palabra distinta.'], salida: [{ name: 'Leonardo AI', url: 'https://leonardo.ai' }] },
        { titulo: 'Sprint 2 · Tu voz, IA', min: 10, pasos: ['Usa ElevenLabs para crear un audio corto con tu voz o una voz predefinida, leyendo un mensaje motivacional para el equipo o la familia.'], salida: [{ name: 'ElevenLabs', url: 'https://elevenlabs.io' }] },
        { titulo: 'Sprint 3 · Canción exprés', min: 15, pasos: ['Genera una canción corta en Suno sobre un tema random: tu equipo, tu videojuego favorito, un chiste interno familiar.'], salida: [{ name: 'Suno', url: 'https://suno.com' }] },
      ] },
      faro: { resumen: 'Proyectos creativos con más intención y reflexión.', sesiones: [
        { titulo: 'Sesión 1 · Moodboard de un proyecto propio', min: 45, pasos: ['Diseña un moodboard visual para algo tuyo usando Midjourney o Leonardo.', 'Itera el prompt aplicando PIENSA al menos 3 veces hasta acercarte a lo que imaginabas.'], salida: [{ name: 'Midjourney', url: 'https://www.midjourney.com' }, { name: 'Leonardo AI', url: 'https://leonardo.ai' }] },
        { titulo: 'Sesión 2 · Narración con voz y música', min: 50, pasos: ['Escribe una historia corta o un poema propio.', 'Nárralo con voz IA y ponle música de fondo generada con Suno.', 'Reflexiona: ¿qué se ganó y qué se perdió al usar IA en vez de hacerlo todo tú misma?'], salida: [{ name: 'ElevenLabs', url: 'https://elevenlabs.io' }, { name: 'Suno', url: 'https://suno.com' }] },
      ] },
      encuentro: { titulo: 'Batalla Creativa', duracion: '30-40 min · todos juntos', pasos: ['Ambos reciben el mismo prompt, cada uno en una herramienta distinta.', 'Votación familiar: ¿cuál imagen o audio ganó y por qué? Usen sentido común: fidelidad al prompt, calidad, sorpresa.'] },
      auto: ['¿Iteré el prompt al menos 2 veces antes de conformarme con el resultado?', '¿Puedo explicar por qué una versión salió mejor que otra?', '¿Reconozco un "error típico" de la IA generativa?'],
      alerta: 'Regla familiar sin excepciones: nunca generar imagen, voz o video de una persona real (conocida o famosa) sin su consentimiento explícito.',
    },
    {
      n: 4,
      titulo: 'Automatizar con IA: agentes y flujos',
      mision: 'Aprender a descomponer una tarea repetitiva en pasos lógicos claros — "si pasa esto, entonces haz esto" — la misma lógica de programar, sin necesitar código.',
      porque: 'Esta es la habilidad que más se va a pedir en cualquier trabajo de los próximos 10 años: pensar en procesos con la claridad suficiente para que una máquina los pueda ejecutar sin ti.',
      tools: [
        { name: 'GPTs personalizados / Gems', use: 'Asistente propio con instrucciones fijas', url: 'https://chatgpt.com', age: '13+' },
        { name: 'n8n', use: 'Automatización visual de tareas entre apps', url: 'https://n8n.io', age: 'Con supervisión' },
        { name: 'Zapier', use: 'Conectar apps con plantillas listas', url: 'https://zapier.com', age: 'Con supervisión' },
        { name: 'Gumloop', use: 'Automatización sin código, fácil para empezar', url: 'https://www.gumloop.com', age: 'Con supervisión' },
      ],
      rayo: { resumen: '3 sprints, empezando en papel antes de tocar una herramienta.', sprints: [
        { titulo: 'Sprint 1 · Si-Entonces en papel', min: 10, pasos: ['Elige una tarea repetitiva de tu rutina.', 'Escribe la lógica en pasos "si pasa esto → entonces hago esto", sin usar ninguna herramienta todavía.'], salida: null },
        { titulo: 'Sprint 2 · Tu propio asistente', min: 15, pasos: ['Crea un GPT personalizado o un Gem que responda siempre en un formato fijo para algo tuyo.', 'Pruébalo 3 veces y ajusta las instrucciones si no sale como querías.'], salida: [{ name: 'ChatGPT (GPTs)', url: 'https://chatgpt.com' }] },
        { titulo: 'Sprint 3 · Automatización real', min: 15, pasos: ['Con supervisión de papá, prueba una plantilla gratuita de Zapier o n8n que conecte dos apps que ya usas.'], salida: [{ name: 'Zapier', url: 'https://zapier.com' }, { name: 'n8n', url: 'https://n8n.io' }] },
      ] },
      faro: { resumen: 'Diseño de flujo completo + asistente personalizado documentado.', sesiones: [
        { titulo: 'Sesión 1 · Diseña el flujo completo', min: 45, pasos: ['Elige una automatización útil para la familia o para ti.', 'Dibuja el flujo lógico completo en papel antes de tocar cualquier herramienta.', 'Intenta construir una versión simple con la herramienta que mejor se ajuste.'], salida: [{ name: 'n8n', url: 'https://n8n.io' }, { name: 'Gumloop', url: 'https://www.gumloop.com' }] },
        { titulo: 'Sesión 2 · Tu asistente personalizado', min: 45, pasos: ['Crea un GPT/Gem para un propósito propio (corrector de estilo, tutor de repaso).', 'Documenta qué instrucciones funcionaron, cuáles no, y cómo las ajustaste.'], salida: [{ name: 'ChatGPT (GPTs)', url: 'https://chatgpt.com' }] },
      ] },
      encuentro: { titulo: 'Reto de la Cadena Familiar', duracion: '40 min · todos juntos', pasos: ['Diseñen juntos, en papel primero, una automatización real y útil para la casa.', 'Pruébenla con una herramienta gratuita, con papá supervisando cualquier conexión a cuentas familiares.'] },
      auto: ['¿Descompuse la tarea en pasos "si-entonces" claros antes de usar la herramienta?', '¿La automatización hizo lo que yo esperaba?', 'Si falló, ¿pude identificar en qué paso lógico se rompió, sin ayuda externa?'],
      alerta: 'No conectar cuentas con datos financieros o personales sensibles de la familia a herramientas de automatización sin la supervisión directa de papá.',
    },
    {
      n: 5,
      titulo: 'Proyecto final: crea algo que valga',
      mision: 'Construir desde cero un proyecto propio (producto, servicio o contenido) que resuelva un problema real, validarlo con al menos una persona fuera de la familia, y demostrar con evidencia — no con opiniones — que generó valor. Ojalá también dinero.',
      porque: 'La prueba final de que aprendieron a pensar con lógica y no a memorizar es esta: crear algo nuevo que otra persona real valore lo suficiente para usarlo, recomendarlo o pagar por ello. Ninguna IA puede hacerles ese favor — solo puede ayudarles a construirlo más rápido. Una idea sin validar es solo una opinión con buen diseño.',
      tools: [
        { name: 'Herramientas de semanas 1-4', use: 'Combinadas según el proyecto elegido, para investigar, crear o automatizar', url: 'https://www.perplexity.ai', age: 'Según cada app' },
        { name: 'Perplexity', use: 'Investigar si el problema ya lo resuelve alguien, y a qué precio', url: 'https://www.perplexity.ai', age: '13+' },
      ],
      rayo: { resumen: 'Reto de 5 días, de la idea al primer cliente real: encuentra un problema pequeño, valídalo antes de construir, crea la versión mínima que funcione, entrégala a alguien real y ajusta con su retroalimentación.', sprints: [
        { titulo: 'Día 1 · Encuentra el problema', min: 20, pasos: ['Piensa en 3 problemas reales y pequeños que tú, tu familia o tus vecinos tengan.', 'Usa una IA de texto para discutir cuál de los 3 es más viable de resolver en una semana. Aplica PIENSA para definirlo con precisión.', 'Elige uno solo. Escríbelo en una frase: "Ayudo a ___ a resolver ___".'], salida: [{ name: 'ChatGPT', url: 'https://chatgpt.com' }] },
        { titulo: 'Día 2 · Valídalo antes de construir', min: 15, pasos: ['Habla o escribe a al menos 2 personas reales fuera de la familia (vecinos, amigos, compañeros).', 'Pregúntales si tienen ese problema y si usarían o pagarían por una solución.', 'Anota sus respuestas EXACTAS, no lo que crees que quisieron decir. Si los dos dicen que no les interesa, vuelve al Día 1.'], salida: null },
        { titulo: 'Día 3 · Construye lo mínimo que funcione', min: 20, pasos: ['Usa las IA de las semanas 1-4 para crear la versión más simple posible de tu producto, servicio o contenido.', 'La meta no es que sea perfecto: es que ya se pueda entregar HOY a una persona real.'], salida: [{ name: 'Elige según tu proyecto (semanas 1-4)', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Día 4 · Entrégalo a un cliente real', min: 20, pasos: ['Entrega o muestra tu creación a esas mismas personas (o a alguien nuevo).', 'Pide que te paguen, te den algo a cambio, o al menos que confirmen honestamente si les sirvió.', 'Guarda la evidencia: una captura, un mensaje, una foto, lo que sea que pruebe que esto pasó de verdad.'], salida: null },
        { titulo: 'Día 5 · Ajusta y prepara tu defensa', min: 20, pasos: ['Con la retroalimentación real, mejora una sola cosa concreta de tu proyecto.', 'Prepara tu presentación de 5 minutos para la Feria IA familiar, mostrando la evidencia real y no solo la idea.'], salida: null },
      ] },
      faro: { resumen: 'Un proyecto propio construido y validado con personas reales fuera de la familia, en 4 sesiones: investigación de mercado, construcción del MVP, validación real, y presentación con datos — no solo con narrativa.', sesiones: [
        { titulo: 'Sesión 1 · Investiga el problema y el mercado', min: 60, pasos: ['Usa IA de investigación (Perplexity) para identificar un problema real, pequeño y no resuelto cerca de ti.', 'Entrevista a al menos 3 personas reales fuera de la familia sobre ese problema.', 'Documenta sus respuestas tal cual las dijeron, sin interpretarlas todavía.'], salida: [{ name: 'Perplexity', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Sesión 2 · Construye tu MVP con IA', min: 60, pasos: ['Diseña y construye la versión mínima de tu producto, servicio o contenido usando las herramientas de las semanas 1-4.', 'El objetivo es que exista algo real y entregable, no solo un plan bonito.'], salida: [{ name: 'Elige según tu proyecto (semanas 1-4)', url: 'https://www.perplexity.ai' }] },
        { titulo: 'Sesión 3 · Valida con usuarios reales', min: 60, pasos: ['Entrega tu MVP a personas reales fuera de la familia.', 'Recoge retroalimentación estructurada: qué les gustó, qué no, si pagarían o lo recomendarían.', 'Si es posible, consigue un intercambio real de valor: dinero, un favor, o el compromiso de usarlo de nuevo.'], salida: null },
        { titulo: 'Sesión 4 · Datos, reflexión y presentación final', min: 45, pasos: ['Documenta con evidencia (no solo tu opinión) cuánto valor generó tu proyecto: cuántas personas lo probaron, qué dijeron, qué ganaste o aprendiste.', 'Prepara tu presentación para la Feria IA familiar apoyada en esos datos reales.'], salida: null },
      ] },
      encuentro: { titulo: 'Feria IA Familiar', duracion: '45-60 min · todos juntos', pasos: ['Cada uno presenta su proyecto a la familia (5-8 minutos), mostrando evidencia real de que alguien fuera de la familia lo usó, lo valoró o pagó por él.', 'Explica qué problema resolvía, qué IA usó, cómo aplicó PIENSA, y qué tuvo que verificar o ajustar con sentido común.', 'Papá y el hermano/hermana hacen la pregunta clave — "¿cómo sabes que esto de verdad sirvió, y no solo crees que sirvió?" — y dan retroalimentación con la rúbrica de autoevaluación final.'] },
      auto: ['¿Puedo elegir la herramienta correcta para una tarea nueva sin que nadie me diga cuál usar?', '¿Puedo detectar cuándo una IA se está inventando algo, sin ayuda?', '¿Puedo explicar mis decisiones de proyecto usando lógica y no solo "porque la IA lo dijo"?', '¿Tengo evidencia real — no solo mi opinión — de que mi proyecto le sirvió a alguien fuera de la familia?', '¿Sé a quién pedir ayuda si algo en una conversación con IA o con una persona real me incomoda?'],
      alerta: 'Antes de hablar con alguien fuera de la familia, mostrar tu proyecto en público o recibir cualquier pago, hazlo siempre con supervisión directa de papá: nunca compartan datos personales, ubicación o información financiera propia o de la familia, y cualquier dinero recibido se entrega y se cuenta junto a un adulto.',
    },
  ],
};
